### ISSUE TITLE
[Enhancement] Json output hairpin

### ISSUE THREAD

**Issue by RoySimons96** [quwubin/MFEprimer-3.0#10]
Hello,

Would it be possible to add the --json/-j output flag for mfeprimer hairpin?

**Comment by quwubin** [comment]
Hi, please test the version 2.2.3: https://github.com/quwubin/MFEprimer-3.0/releases/tag/v3.2.3

**Comment by RoySimons96** [comment]
Thank you for the quick response!
The flag is working as expected.

**Comment by RoySimons96** [comment]
Hi @quwubin,

While working with the --json flag for mfeprimer hairpin I noticed a bug.
The output in JSON format contains a mistake in the hairpin structure. There is double the amount of '\' on the right side of Aseq attribute compared to the text output.
[Hairpin.zip](https://github.com/quwubin/MFEprimer-3.0/files/7045420/Hairpin.zip)

**Comment by quwubin** [comment]
Hi, thanks, I found the reason and I will fix it as soon as I can.

Wubin Qu

Email:   ***@***.***
Scholar: *http://scholar.google.com/citations?user=Ayyglz8AAAAJ&hl=en
<http://scholar.google.com/citations?user=Ayyglz8AAAAJ&hl=en>*

**Comment by quwubin** [comment]
## hairpin json out has double '\\'

The normal txt output is ok, e.g., 


    Score: 9, Tm = 26.56 °C, Delta G = -4.48 kcal/mol

    /////////-------\\\\\\\\\
    GGACACTCTATGGGAAAGAGTGTCC


While in json output, there is doulbe '\\', that's because I need to escape '\\'.

`[{"Seq":{"ID":"p5","Desc":"","Seq":"GGACACTCTATGGGAAAGAGTGTCC"},"Aseq":"/////////-------\\\\\\\\\\\\\\\\\\","Tm":26.562475477440273,"Dg":-4.483902941985449,"Score":9}]
`

Solution 1: if you use Pyhton to read the json out, it just read correctly:

<img width="1283" alt="截屏2021-09-05 下午11 54 06" src="https://user-images.githubusercontent.com/9742/132133197-3bef41e1-40db-4dc5-8daf-9bcdceeec486.png">


Solution 2: if this is still a problem, currently, we need to delete the redundant '\\' by ourselves.
