### ISSUE TITLE
Getting different dimer analysis results while using the same sequences with different order

### ISSUE THREAD

**Issue by SaitouAsuka** [quwubin/MFEprimer-3.0#15]
With default conditions, giving two fastas which are constructed by the same sequences but in the different order,  `mfeprimer dimer`(not matter 3.2.5 or 3.2.0 or 3.2.3) will gives different outputs.
Part of  fasta looks like this:
![{7F2A3CC7-A566-4D00-BA34-614562774BF7}](https://user-images.githubusercontent.com/20475719/169332250-9d078044-cebb-48f0-9f0d-1b24d7893c15.png)
The other fasta looks like this:
![{A683A9AB-2958-41F3-936B-7A97594C8102}](https://user-images.githubusercontent.com/20475719/169332562-7039a015-9945-4e8f-8b79-9ac2399c7d01.png)
I pretty sure the fastas are composed of the same sequences.I check it by python:
![{6900DCAE-3F7C-4577-9776-E05F5A7C190A}](https://user-images.githubusercontent.com/20475719/169332115-aedc8d1f-a6d7-4da5-81b3-b1299e313dc3.png)
But what I got with command `mfeprimer dimer -i temp.fa -p ` are different outputs:
![{EF7AF245-C7A4-4A5E-9A25-45D1C28DB4E7}](https://user-images.githubusercontent.com/20475719/169330377-b48cf294-5679-4c82-bc7d-1537939a25d4.png)
![{B08A4447-327C-4DD4-A988-2AA1AF7FD9CD}](https://user-images.githubusercontent.com/20475719/169330250-3adcf3f6-2e49-4b71-b221-ddc1af76dae3.png)
It really confused me a lot. Are there any special rules for input fastas?
Thanks!

**Comment by quwubin** [comment]
can you send me the primers (in private) and let me find the bug?

my email: quwubin@gmail.com

**Comment by SaitouAsuka** [comment]
> can you send me the primers (in private) and let me find the bug?
> 
> my email: [quwubin@gmail.com](mailto:quwubin@gmail.com)

I sent you an email, plz check ur gmail.

**Comment by quwubin** [comment]
Hi,

Thank you help me find a hidden bug when calculating delta G values.

## bug fixed

`mfeprimer dimer`: fixed a bug when calculating delta G values;

## broken usage update

remove `-t` option for `mfeprimer dimer`, because the Tm for short dimers are not accurate and I recommended use delta G or Score to filter the dimers.

## pre-release test

[mfeprimer-3.2.7-windows-4.0-amd64.exe.gz](https://github.com/quwubin/MFEprimer-3.0/files/8742196/mfeprimer-3.2.7-windows-4.0-amd64.exe.gz)
[mfeprimer-3.2.7-darwin-10.6-amd64.gz](https://github.com/quwubin/MFEprimer-3.0/files/8742190/mfeprimer-3.2.7-darwin-10.6-amd64.gz)
[mfeprimer-3.2.7-linux-amd64.gz](https://github.com/quwubin/MFEprimer-3.0/files/8742193/mfeprimer-3.2.7-linux-amd64.gz)
